import { readFileSync, writeFileSync } from "node:fs";
import { resolve, dirname } from "node:path";
import { fileURLToPath } from "node:url";

const __dirname = dirname(fileURLToPath(import.meta.url));
const srcDir = resolve(__dirname, "../src");

const GENERATED_FILES = [
  "PGLLexer.ts",
  "PGLParser.ts",
  "PGLParserListener.ts",
  "PGLParserVisitor.ts",
];

// 1. Rewrite antlr4 imports
for (const file of GENERATED_FILES) {
  const filePath = resolve(srcDir, file);
  let content = readFileSync(filePath, "utf-8");
  const replaced = content.replace(/from\s+['"]antlr4['"]/g, "from '@pglambda/antlr-next'");
  if (replaced === content) {
    console.warn(`WARNING: No antlr4 import found in ${file}`);
  }
  writeFileSync(filePath, replaced, "utf-8");
}

// 2. Extract ruleNames → generate rule-names.ts
const parserContent = readFileSync(resolve(srcDir, "PGLParser.ts"), "utf-8");
const match = parserContent.match(/public static readonly ruleNames: string\[\] = \[([\s\S]*?)\];/);
if (!match) {
  console.error("ERROR: Could not find ruleNames in PGLParser.ts");
  process.exit(1);
}

const ruleNames: string[] = [];
for (const m of match[1].matchAll(/"([^"]+)"/g)) {
  ruleNames.push(m[1]);
}

const typeUnion = ruleNames.map((n) => `  | "${n}"`).join("\n");
const output = [
  "// Auto-generated by scripts/postprocess.ts — do not edit",
  "",
  "export type PGLRuleName =",
  typeUnion + ";",
  "",
].join("\n");

writeFileSync(resolve(srcDir, "rule-names.ts"), output, "utf-8");
console.log(`postprocess: rewrote imports, generated ${ruleNames.length} rule names`);
